import { Router, type IRouter } from "express";
import aiRouter from "./ai";
import authRouter from "./auth";
import captureRouter from "./capture";
import capturesRouter from "./captures";
import connectorsRouter from "./connectors";
import documentsRouter from "./documents";
import evidenceRouter from "./evidence";
import extensionTokensRouter from "./extension-tokens";
import healthRouter from "./health";
import notesRouter from "./notes";
import attachmentsRouter from "./attachments";
import notebooksRouter from "./notebooks";
import peopleRouter from "./people";
import vehiclesRouter from "./vehicles";
import organizationsRouter from "./organizations";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import todayRouter from "./today";
import auditRouter from "./audit";
import memoryRouter from "./memory";
import webhooksHomeyRouter from "./webhooks-homey";
import { requireAuth } from "../middleware/auth";
import { aiRateLimiter } from "../middleware/security";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(webhooksHomeyRouter);
router.use(extensionTokensRouter);
router.use(notebooksRouter);
router.use(notesRouter);
router.use(attachmentsRouter);
router.use(projectsRouter);
router.use(capturesRouter);
router.use(captureRouter);
router.use(evidenceRouter);
router.use(peopleRouter);
router.use(vehiclesRouter);
router.use(organizationsRouter);
router.use(todayRouter);
router.use(connectorsRouter);
router.use(documentsRouter);
router.use(memoryRouter);
router.use(tasksRouter);
router.use(auditRouter);
router.use(aiRateLimiter, requireAuth, aiRouter);

export default router;
